/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.annguyen.kyanhbooks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KhachHang service. Represents a row in the &quot;KhachHang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.annguyen.kyanhbooks.model.impl.KhachHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.annguyen.kyanhbooks.model.impl.KhachHangImpl}.
 * </p>
 *
 * @author AnNguyen
 * @see KhachHang
 * @see com.annguyen.kyanhbooks.model.impl.KhachHangImpl
 * @see com.annguyen.kyanhbooks.model.impl.KhachHangModelImpl
 * @generated
 */
public interface KhachHangModel extends BaseModel<KhachHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a khach hang model instance should use the {@link KhachHang} interface instead.
	 */

	/**
	 * Returns the primary key of this khach hang.
	 *
	 * @return the primary key of this khach hang
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this khach hang.
	 *
	 * @param primaryKey the primary key of this khach hang
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ma k h of this khach hang.
	 *
	 * @return the ma k h of this khach hang
	 */
	public int getMaKH();

	/**
	 * Sets the ma k h of this khach hang.
	 *
	 * @param MaKH the ma k h of this khach hang
	 */
	public void setMaKH(int MaKH);

	/**
	 * Returns the ten k h of this khach hang.
	 *
	 * @return the ten k h of this khach hang
	 */
	@AutoEscape
	public String getTenKH();

	/**
	 * Sets the ten k h of this khach hang.
	 *
	 * @param TenKH the ten k h of this khach hang
	 */
	public void setTenKH(String TenKH);

	/**
	 * Returns the mat khau of this khach hang.
	 *
	 * @return the mat khau of this khach hang
	 */
	@AutoEscape
	public String getMatKhau();

	/**
	 * Sets the mat khau of this khach hang.
	 *
	 * @param MatKhau the mat khau of this khach hang
	 */
	public void setMatKhau(String MatKhau);

	/**
	 * Returns the email of this khach hang.
	 *
	 * @return the email of this khach hang
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this khach hang.
	 *
	 * @param Email the email of this khach hang
	 */
	public void setEmail(String Email);

	/**
	 * Returns the dien thoai of this khach hang.
	 *
	 * @return the dien thoai of this khach hang
	 */
	@AutoEscape
	public String getDienThoai();

	/**
	 * Sets the dien thoai of this khach hang.
	 *
	 * @param DienThoai the dien thoai of this khach hang
	 */
	public void setDienThoai(String DienThoai);

	/**
	 * Returns the gioi tinh of this khach hang.
	 *
	 * @return the gioi tinh of this khach hang
	 */
	public boolean getGioiTinh();

	/**
	 * Returns <code>true</code> if this khach hang is gioi tinh.
	 *
	 * @return <code>true</code> if this khach hang is gioi tinh; <code>false</code> otherwise
	 */
	public boolean isGioiTinh();

	/**
	 * Sets whether this khach hang is gioi tinh.
	 *
	 * @param GioiTinh the gioi tinh of this khach hang
	 */
	public void setGioiTinh(boolean GioiTinh);

	/**
	 * Returns the ngay sinh of this khach hang.
	 *
	 * @return the ngay sinh of this khach hang
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this khach hang.
	 *
	 * @param NgaySinh the ngay sinh of this khach hang
	 */
	public void setNgaySinh(Date NgaySinh);

	/**
	 * Returns the dia chi of this khach hang.
	 *
	 * @return the dia chi of this khach hang
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this khach hang.
	 *
	 * @param DiaChi  the dia chi of this khach hang
	 */
	public void setDiaChi(String DiaChi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.annguyen.kyanhbooks.model.KhachHang khachHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.annguyen.kyanhbooks.model.KhachHang> toCacheModel();

	@Override
	public com.annguyen.kyanhbooks.model.KhachHang toEscapedModel();

	@Override
	public com.annguyen.kyanhbooks.model.KhachHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}