/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.annguyen.kyanhbooks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LoaiSach service. Represents a row in the &quot;LoaiSach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.annguyen.kyanhbooks.model.impl.LoaiSachModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.annguyen.kyanhbooks.model.impl.LoaiSachImpl}.
 * </p>
 *
 * @author AnNguyen
 * @see LoaiSach
 * @see com.annguyen.kyanhbooks.model.impl.LoaiSachImpl
 * @see com.annguyen.kyanhbooks.model.impl.LoaiSachModelImpl
 * @generated
 */
public interface LoaiSachModel extends BaseModel<LoaiSach> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai sach model instance should use the {@link LoaiSach} interface instead.
	 */

	/**
	 * Returns the primary key of this loai sach.
	 *
	 * @return the primary key of this loai sach
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this loai sach.
	 *
	 * @param primaryKey the primary key of this loai sach
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ma loai sach of this loai sach.
	 *
	 * @return the ma loai sach of this loai sach
	 */
	@AutoEscape
	public String getMaLoaiSach();

	/**
	 * Sets the ma loai sach of this loai sach.
	 *
	 * @param MaLoaiSach the ma loai sach of this loai sach
	 */
	public void setMaLoaiSach(String MaLoaiSach);

	/**
	 * Returns the ten loai sach of this loai sach.
	 *
	 * @return the ten loai sach of this loai sach
	 */
	@AutoEscape
	public String getTenLoaiSach();

	/**
	 * Sets the ten loai sach of this loai sach.
	 *
	 * @param TenLoaiSach the ten loai sach of this loai sach
	 */
	public void setTenLoaiSach(String TenLoaiSach);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.annguyen.kyanhbooks.model.LoaiSach loaiSach);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.annguyen.kyanhbooks.model.LoaiSach> toCacheModel();

	@Override
	public com.annguyen.kyanhbooks.model.LoaiSach toEscapedModel();

	@Override
	public com.annguyen.kyanhbooks.model.LoaiSach toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}