/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.annguyen.kyanhbooks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Sach service. Represents a row in the &quot;Sach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.annguyen.kyanhbooks.model.impl.SachModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.annguyen.kyanhbooks.model.impl.SachImpl}.
 * </p>
 *
 * @author AnNguyen
 * @see Sach
 * @see com.annguyen.kyanhbooks.model.impl.SachImpl
 * @see com.annguyen.kyanhbooks.model.impl.SachModelImpl
 * @generated
 */
public interface SachModel extends BaseModel<Sach> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sach model instance should use the {@link Sach} interface instead.
	 */

	/**
	 * Returns the primary key of this sach.
	 *
	 * @return the primary key of this sach
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this sach.
	 *
	 * @param primaryKey the primary key of this sach
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ma sach of this sach.
	 *
	 * @return the ma sach of this sach
	 */
	@AutoEscape
	public String getMaSach();

	/**
	 * Sets the ma sach of this sach.
	 *
	 * @param MaSach the ma sach of this sach
	 */
	public void setMaSach(String MaSach);

	/**
	 * Returns the ten sach of this sach.
	 *
	 * @return the ten sach of this sach
	 */
	@AutoEscape
	public String getTenSach();

	/**
	 * Sets the ten sach of this sach.
	 *
	 * @param TenSach the ten sach of this sach
	 */
	public void setTenSach(String TenSach);

	/**
	 * Returns the don gia of this sach.
	 *
	 * @return the don gia of this sach
	 */
	public float getDonGia();

	/**
	 * Sets the don gia of this sach.
	 *
	 * @param DonGia the don gia of this sach
	 */
	public void setDonGia(float DonGia);

	/**
	 * Returns the so luong of this sach.
	 *
	 * @return the so luong of this sach
	 */
	public int getSoLuong();

	/**
	 * Sets the so luong of this sach.
	 *
	 * @param SoLuong the so luong of this sach
	 */
	public void setSoLuong(int SoLuong);

	/**
	 * Returns the url hinh of this sach.
	 *
	 * @return the url hinh of this sach
	 */
	@AutoEscape
	public String getUrlHinh();

	/**
	 * Sets the url hinh of this sach.
	 *
	 * @param UrlHinh the url hinh of this sach
	 */
	public void setUrlHinh(String UrlHinh);

	/**
	 * Returns the noi dung of this sach.
	 *
	 * @return the noi dung of this sach
	 */
	@AutoEscape
	public String getNoiDung();

	/**
	 * Sets the noi dung of this sach.
	 *
	 * @param NoiDung the noi dung of this sach
	 */
	public void setNoiDung(String NoiDung);

	/**
	 * Returns the tac gia of this sach.
	 *
	 * @return the tac gia of this sach
	 */
	@AutoEscape
	public String getTacGia();

	/**
	 * Sets the tac gia of this sach.
	 *
	 * @param TacGia the tac gia of this sach
	 */
	public void setTacGia(String TacGia);

	/**
	 * Returns the nam x b of this sach.
	 *
	 * @return the nam x b of this sach
	 */
	public int getNamXB();

	/**
	 * Sets the nam x b of this sach.
	 *
	 * @param NamXB the nam x b of this sach
	 */
	public void setNamXB(int NamXB);

	/**
	 * Returns the n x b of this sach.
	 *
	 * @return the n x b of this sach
	 */
	@AutoEscape
	public String getNXB();

	/**
	 * Sets the n x b of this sach.
	 *
	 * @param NXB the n x b of this sach
	 */
	public void setNXB(String NXB);

	/**
	 * Returns the ma loai sach of this sach.
	 *
	 * @return the ma loai sach of this sach
	 */
	@AutoEscape
	public String getMaLoaiSach();

	/**
	 * Sets the ma loai sach of this sach.
	 *
	 * @param MaLoaiSach the ma loai sach of this sach
	 */
	public void setMaLoaiSach(String MaLoaiSach);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.annguyen.kyanhbooks.model.Sach sach);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.annguyen.kyanhbooks.model.Sach> toCacheModel();

	@Override
	public com.annguyen.kyanhbooks.model.Sach toEscapedModel();

	@Override
	public com.annguyen.kyanhbooks.model.Sach toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}